META_ARC: "siamgat_googlenet"

BACKBONE:
    TYPE: "googlenet"
    PRETRAINED: 'pretrained_models/inception_v3.pth'
    TRAIN_LAYERS: ['Mixed_5b','Mixed_5c','Mixed_5d', 'Mixed_6a', 'Mixed_6b', 'Mixed_6c', 'Mixed_6d', 'Mixed_6e', 'channel_reduce']
    CHANNEL_REDUCE_LAYERS: ['channel_reduce']
    TRAIN_EPOCH: 10
    CROP_PAD: 4
    LAYERS_LR: 0.1

TRACK:
    TYPE: 'SiamGATTracker'
    EXEMPLAR_SIZE: 127
    INSTANCE_SIZE: 287
    SCORE_SIZE: 25
    CONTEXT_AMOUNT: 0.5
    STRIDE: 8
    OFFSET: 45
